name: Flujo de trabajo que se ejecuta con los issues
on:
  workflow_dispatch:
  issues:
    types: [opened, transferred]
jobs:
  comment_on_new_issue:
    runs-on: ubuntu-latest
    name: Job for commenting on new issue
    steps:
      - name: Comment
        uses: jd-0001/gh-action-comment-on-new-issue@v2.0.3
        with:
          message: 'Welcome to the repo :)'
